### ISSUE TITLE
Support cookies

### ISSUE THREAD

**Issue by Asimov4** [abhikmitra/ng-joyride#16]
It would be nice to see support for cookies to only display the joyride walkthrough the first time like in jQuery Joyride.
```
  'cookieMonster': true,           // true/false for whether cookies are used
  'cookieName': 'JoyRide',         // choose your own cookie name
  'cookieDomain': false,           // set to false or yoursite.com
```

From http://zurb.com/playground/jquery-joyride-feature-tour-plugin

**Comment by abhikmitra** [comment]
I am not too crazy about cookies cause it can be easily done externally as well. Let me think about it
