### ISSUE TITLE
boostrap.js dependency ?

### ISSUE THREAD

**Issue by bixibu** [abhikmitra/ng-joyride#17]
Hi

I'm trying to integrate your module in my app but I get an error : 
TypeError: undefined is not a function
    at Object._generatePopover (http://127.0.0.1:9002/vendor/ng-joyride/ng-joyride.js:105:23)

On your demo I saw that you're loading bootstrap.js (I don't), but this should not be needed because in parallel you're loading  angular-bootstrap module (ui-bootstrap-tpls.js)  that already handle himself (the angular-way) all the JS needed to run bootstrap JS components.

Or am I missing something ?

By the way, thanks for this module that seems great ;)

**Comment by bbeyssac** [comment]
Hello,

I have the exact same problem and I don't have bootstrap in my project. We use foundation. Is bootstrap mandatory or is this a bug ?

Thanks.

**Comment by abhikmitra** [comment]
Yes Bootstrap is mandatory . It uses bootstrap popovers .

**Comment by bixibu** [comment]
Hu..

So why are you loading angular-bootstrap (ui-bootstrap-tpls.js) in your demos ?
Angular-bootstrap includes popovers already (but angularjsfied)

**Comment by bbeyssac** [comment]
I will be out of the office until February 6th with limited email access.

For a technical request, please send your message to support@c6.eu.

For other requests, please contact contact@c6.eu.



> From: bixibu <notifications@github.com>
> Subject: Re: [ng-joyride] boostrap.js dependency ? (#17)
> Date: Thu, 29 Jan 2015 05:08:31 -0800
