### ISSUE TITLE
Skip elements not present?

### ISSUE THREAD

**Issue by Frenjon** [abhikmitra/ng-joyride#22]
Hi

Is it somehow possible to skip non-present elements and jump to the next element that's present?

I'm trying to setup ng-joyride on a page where certain users don't have access to a specific element on the site. It's hidden from view (yes I know - not the most elegant solution).

When ng-joyride comes to the missing element only the curtain in shown.

**Comment by abhikmitra** [comment]
Well you always have your config. Change your config according to the current user.
