### ISSUE TITLE
Two title steps in a row causes failure

### ISSUE THREAD

**Issue by yaronguez** [abhikmitra/ng-joyride#25]
If two title steps occur in a row the second step closes immediately leaving the user with the curtain and no other modals to click through.  I've confirmed this in the demo so I know it's not an issue my environment or project.  Any ideas?

**Comment by abhikmitra** [comment]
@yaronguez I have updated the joyride to fix the issue. I have also updated the demo, to involve 2 consecutive title step .

**Comment by yaronguez** [comment]
Thanks!
