### ISSUE TITLE
bootstrap version in bower.json

### ISSUE THREAD

**Issue by steve-tapley** [abhikmitra/ng-joyride#27]
Hi,
I was wondering if there is a reason your bower.json file specifies bootstrap version 3.2.0?   I'm having issues because ng-joyride is requiring 3.2.0 (and I have other dependencies using a later version) - is it possible to change the bower.json to something like:

`"bootstrap": "~3.2.0"`

Thanks,
Steve

**Comment by abhikmitra** [comment]
Go ahead. Send a PR please.

-----Original Message-----
