### ISSUE TITLE
curtainClass being overridden by id

### ISSUE THREAD

**Issue by pparsons** [abhikmitra/ng-joyride#31]
Just started using ng-joyride, and it is very nice. However, I'm running into a problem with using the curtainClass property on an element. If I create a CSS class that should override some of the default properties (e.g., override the opacity or color of the curtain) it won't work because the defaults are set on a CSS id (#ng-curtain), and CSS gives precedence to ids over classes.

So trying to override any of the default properties with the curtainClass will never work. Am I missing something?

**Comment by abhikmitra** [comment]
Correct! Let me fix this today and trigger a new release.

**Comment by pparsons** [comment]
I've tried the new release but the issue seems to be still there unless I'm missing something. Any properties I set on the custom curtainClass are still being overridden by "#ng-curtain" because ids take precedence over classes.

**Comment by abhikmitra** [comment]
Sorry about that. I forgot to commit the css file.  I put out another release and also updated the demo. Can you please check. Extremely sorry for the inconvenience.

**Comment by pparsons** [comment]
Great, it appears to work now. Thanks!
