### ISSUE TITLE
Curtain is shown, empty popup

### ISSUE THREAD

**Issue by mleonelli** [abhikmitra/ng-joyride#35]
Hi Abhik,
trying to find the root cause for it, page loads curtain and title but the popup is empty.
No JS errors in console.
```html
<div id="ng-curtain" class="ng-curtain-class" style="display: block;"></div>
<div class="ng-joyride-title" style=""></div>
```

**Comment by abhikmitra** [comment]
can you replicate in a small plunkr ?
