### ISSUE TITLE
AdvanceOn event watchers remain after Skip

### ISSUE THREAD

**Issue by hugo-azevedo** [abhikmitra/ng-joyride#38]
When the "Skip" button is clicked on an element popover that has an advanceOn option set for a click event, the event click remains. So, after the curtain has disappeared and the tour has ended, if the user clicks the element registered with the advanceOn, the tour resumes without the curtain.

Is there a specific call necessary to clear all tour related event watchers?
Thanks

**Comment by abhikmitra** [comment]
Can you provide a plunkr ?

**Comment by hugo-azevedo** [comment]
Here you go!
http://plnkr.co/8xsZvrhEAKaIJoJVphCj

**Comment by hugo-azevedo** [comment]
Sorry closed it by mistake.

**Comment by abhikmitra** [comment]
I released an update , please use 0.1.16 version .

**Comment by hugo-azevedo** [comment]
Thanks very much! I'll give it a go tomorrow!

**Comment by hugo-azevedo** [comment]
Hi, there!
I've tested it and it does indeed unbind the advanceOn event.

However, when using angular-route, the unBindAdvanceOn function seems to unbind ALL events for that specific DOM and the routing stops working. I've updated the plunkr to show this.

If you press "Skip" at step2 (as before) then clicking on Option2 doesn't take you to Option2.html.
If you cancel the tour at the title popover, you can see that Option2 works fine if the unBindAdvanceOn hasn't been run.

Thanks again!

**Comment by abhikmitra** [comment]
Reopening this again

**Comment by hugo-azevedo** [comment]
Thanks!

**Comment by abhikmitra** [comment]
Fixed in the latest release. Can you check and close ?

**Comment by hugo-azevedo** [comment]
Perfect! Thank you very much for your prompt efforts!
Much obliged!

**Comment by hugo-azevedo** [comment]
Hi,
I believe I've found a bug with the new unBindAdvanceOn() functionality.

When it is called on a title element, the error "*TypeError: Cannot read property 'off' of undefined*" is printed to console. As a consequence the tour cannot be restarted and the same error is printed to console every time it is tried.

Unfortunately I reused the above plunkr for issue #39 that I submitted earlier today, but you can still reproduce the bug on this plunkr by clicking Skip on the welcome title popover. Check the browser console for the error.

Many thanks in advance and sorry for the back to back issue raising.

**Comment by abhikmitra** [comment]
Thanks to you for catching the bugs.Do keep on raising bugs. 

I fixed it . Check and close

**Comment by hugo-azevedo** [comment]
Confirmed! Thanks very much!
