### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by kcaron-cst** [abhikmitra/ng-joyride#42]
Forgive me but I am removing bower dependencies and I needed a version of this package provided by NPM as we are removing bower from our build system.

https://www.npmjs.com/package/ng-joyride

Please let me know your NPM username and I'll make you an owner of the npm package and remove myself from it ASAP. If for whatever reason you need the package to be unpublished, let me know and I will immediately.

**Comment by abhikmitra** [comment]
username : abhikmitra 
Thanks for the effort :+1:

**Comment by kcaron-cst** [comment]
Excellent! Added. Thanks for the great module
