### ISSUE TITLE
Bootstrap independent

### ISSUE THREAD

**Issue by silvestreh** [abhikmitra/ng-joyride#43]
Please, do make this _NOT_ require bootstrap.

**Comment by silvestreh** [comment]
It seems, style-wise at least, that you only need the styles for `.popover` …

**Comment by laurent-le-graverend** [comment]
:+1:

**Comment by kmgilbert100** [comment]
Please ^

**Comment by abhikmitra** [comment]
Not requiring bootstrap will be a big effort since the popovers are basically bootstrap popovers

**Comment by masimakopoulos** [comment]
+1 on removing bootstrap dependency. This is an excellent module, but bootstrap dependency is a show stopper for most projects not already using bootstrap
